/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TechnologiesRouteImport } from './routes/technologies'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioTheBuilderCoilRouteImport } from './routes/portfolio/the-builder-coil'
import { Route as PortfolioSkyscraperRouteImport } from './routes/portfolio/skyscraper'
import { Route as PortfolioShippingApiDojoRouteImport } from './routes/portfolio/shipping-api-dojo'
import { Route as PortfolioJorildSeRouteImport } from './routes/portfolio/jorild-se'
import { Route as PortfolioChronomationRouteImport } from './routes/portfolio/chronomation'
import { Route as PortfolioBlightfellRouteImport } from './routes/portfolio/blightfell'

const TechnologiesRoute = TechnologiesRouteImport.update({
  id: '/technologies',
  path: '/technologies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioTheBuilderCoilRoute = PortfolioTheBuilderCoilRouteImport.update({
  id: '/portfolio/the-builder-coil',
  path: '/portfolio/the-builder-coil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSkyscraperRoute = PortfolioSkyscraperRouteImport.update({
  id: '/portfolio/skyscraper',
  path: '/portfolio/skyscraper',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioShippingApiDojoRoute =
  PortfolioShippingApiDojoRouteImport.update({
    id: '/portfolio/shipping-api-dojo',
    path: '/portfolio/shipping-api-dojo',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioJorildSeRoute = PortfolioJorildSeRouteImport.update({
  id: '/portfolio/jorild-se',
  path: '/portfolio/jorild-se',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioChronomationRoute = PortfolioChronomationRouteImport.update({
  id: '/portfolio/chronomation',
  path: '/portfolio/chronomation',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioBlightfellRoute = PortfolioBlightfellRouteImport.update({
  id: '/portfolio/blightfell',
  path: '/portfolio/blightfell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/portfolio/blightfell': typeof PortfolioBlightfellRoute
  '/portfolio/chronomation': typeof PortfolioChronomationRoute
  '/portfolio/jorild-se': typeof PortfolioJorildSeRoute
  '/portfolio/shipping-api-dojo': typeof PortfolioShippingApiDojoRoute
  '/portfolio/skyscraper': typeof PortfolioSkyscraperRoute
  '/portfolio/the-builder-coil': typeof PortfolioTheBuilderCoilRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/portfolio/blightfell': typeof PortfolioBlightfellRoute
  '/portfolio/chronomation': typeof PortfolioChronomationRoute
  '/portfolio/jorild-se': typeof PortfolioJorildSeRoute
  '/portfolio/shipping-api-dojo': typeof PortfolioShippingApiDojoRoute
  '/portfolio/skyscraper': typeof PortfolioSkyscraperRoute
  '/portfolio/the-builder-coil': typeof PortfolioTheBuilderCoilRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/technologies': typeof TechnologiesRoute
  '/portfolio/blightfell': typeof PortfolioBlightfellRoute
  '/portfolio/chronomation': typeof PortfolioChronomationRoute
  '/portfolio/jorild-se': typeof PortfolioJorildSeRoute
  '/portfolio/shipping-api-dojo': typeof PortfolioShippingApiDojoRoute
  '/portfolio/skyscraper': typeof PortfolioSkyscraperRoute
  '/portfolio/the-builder-coil': typeof PortfolioTheBuilderCoilRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/services'
    | '/technologies'
    | '/portfolio/blightfell'
    | '/portfolio/chronomation'
    | '/portfolio/jorild-se'
    | '/portfolio/shipping-api-dojo'
    | '/portfolio/skyscraper'
    | '/portfolio/the-builder-coil'
    | '/portfolio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/services'
    | '/technologies'
    | '/portfolio/blightfell'
    | '/portfolio/chronomation'
    | '/portfolio/jorild-se'
    | '/portfolio/shipping-api-dojo'
    | '/portfolio/skyscraper'
    | '/portfolio/the-builder-coil'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/services'
    | '/technologies'
    | '/portfolio/blightfell'
    | '/portfolio/chronomation'
    | '/portfolio/jorild-se'
    | '/portfolio/shipping-api-dojo'
    | '/portfolio/skyscraper'
    | '/portfolio/the-builder-coil'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  TechnologiesRoute: typeof TechnologiesRoute
  PortfolioBlightfellRoute: typeof PortfolioBlightfellRoute
  PortfolioChronomationRoute: typeof PortfolioChronomationRoute
  PortfolioJorildSeRoute: typeof PortfolioJorildSeRoute
  PortfolioShippingApiDojoRoute: typeof PortfolioShippingApiDojoRoute
  PortfolioSkyscraperRoute: typeof PortfolioSkyscraperRoute
  PortfolioTheBuilderCoilRoute: typeof PortfolioTheBuilderCoilRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/technologies': {
      id: '/technologies'
      path: '/technologies'
      fullPath: '/technologies'
      preLoaderRoute: typeof TechnologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/the-builder-coil': {
      id: '/portfolio/the-builder-coil'
      path: '/portfolio/the-builder-coil'
      fullPath: '/portfolio/the-builder-coil'
      preLoaderRoute: typeof PortfolioTheBuilderCoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/skyscraper': {
      id: '/portfolio/skyscraper'
      path: '/portfolio/skyscraper'
      fullPath: '/portfolio/skyscraper'
      preLoaderRoute: typeof PortfolioSkyscraperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/shipping-api-dojo': {
      id: '/portfolio/shipping-api-dojo'
      path: '/portfolio/shipping-api-dojo'
      fullPath: '/portfolio/shipping-api-dojo'
      preLoaderRoute: typeof PortfolioShippingApiDojoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/jorild-se': {
      id: '/portfolio/jorild-se'
      path: '/portfolio/jorild-se'
      fullPath: '/portfolio/jorild-se'
      preLoaderRoute: typeof PortfolioJorildSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/chronomation': {
      id: '/portfolio/chronomation'
      path: '/portfolio/chronomation'
      fullPath: '/portfolio/chronomation'
      preLoaderRoute: typeof PortfolioChronomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/blightfell': {
      id: '/portfolio/blightfell'
      path: '/portfolio/blightfell'
      fullPath: '/portfolio/blightfell'
      preLoaderRoute: typeof PortfolioBlightfellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  TechnologiesRoute: TechnologiesRoute,
  PortfolioBlightfellRoute: PortfolioBlightfellRoute,
  PortfolioChronomationRoute: PortfolioChronomationRoute,
  PortfolioJorildSeRoute: PortfolioJorildSeRoute,
  PortfolioShippingApiDojoRoute: PortfolioShippingApiDojoRoute,
  PortfolioSkyscraperRoute: PortfolioSkyscraperRoute,
  PortfolioTheBuilderCoilRoute: PortfolioTheBuilderCoilRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
